/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmHistorialJogadores.java
 *
 * Created on 10/11/2011, 13:49:00
 */
package view;

import dao.HistorialJogadoDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando João
 */
public class frmHistorialJogadores extends javax.swing.JDialog {
    
    HistorialJogadoDAO daoHistorial= new HistorialJogadoDAO();
    
    private String[] cabecalho = {"Número", "Clube","Equipa","Data de Início", "Data do Fim"};
    /** Creates new form frmHistorialJogadores */
    public frmHistorialJogadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void actualizaTabela(long numFAF){
        
        Tabela.setModel(new DefaultTableModel(daoHistorial.listarHistorialjogador(numFAF), cabecalho));
    }
    
    public void setNomeNumfaf(String nomeJogador, long numFAF){
        lbl_Nome.setText(nomeJogador);
        lbl_numFAF.setText(""+numFAF+"");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bt_Castigo = new javax.swing.JLabel();
        bt_Adicionar = new javax.swing.JButton();
        bt_Editar = new javax.swing.JButton();
        bt_Remover = new javax.swing.JButton();
        bt_Remover1 = new javax.swing.JButton();
        bt_Jogos = new javax.swing.JLabel();
        bt_Cartoes = new javax.swing.JLabel();
        bt_GolosMarcado = new javax.swing.JLabel();
        bt_GolosSofrido = new javax.swing.JLabel();
        bt_Defesas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lbl_Nome = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_numFAF = new javax.swing.JLabel();

        setModal(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Historial de Jogador © 2011");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12), new java.awt.Color(204, 204, 255))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Historial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18), new java.awt.Color(204, 204, 255))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18));
        jPanel3.setOpaque(false);
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });

        bt_Castigo.setBackground(new java.awt.Color(204, 204, 255));
        bt_Castigo.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        bt_Castigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_Castigo.setText("Castigos Sofridos");
        bt_Castigo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12), new java.awt.Color(204, 204, 255))); // NOI18N
        bt_Castigo.setOpaque(true);
        bt_Castigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CastigoMouseClicked(evt);
            }
        });
        bt_Castigo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_CastigoMouseMoved(evt);
            }
        });

        bt_Adicionar.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        bt_Adicionar.setText("Adicionar");
        bt_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AdicionarActionPerformed(evt);
            }
        });

        bt_Editar.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        bt_Editar.setText("Editar");

        bt_Remover.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        bt_Remover.setText("Remover");

        bt_Remover1.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        bt_Remover1.setText("Detalhes");

        bt_Jogos.setBackground(new java.awt.Color(204, 204, 255));
        bt_Jogos.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        bt_Jogos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_Jogos.setText("Jogos Participados");
        bt_Jogos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12), new java.awt.Color(204, 204, 255))); // NOI18N
        bt_Jogos.setOpaque(true);
        bt_Jogos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_JogosMouseClicked(evt);
            }
        });
        bt_Jogos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_JogosMouseMoved(evt);
            }
        });

        bt_Cartoes.setBackground(new java.awt.Color(204, 204, 255));
        bt_Cartoes.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        bt_Cartoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_Cartoes.setText("Cartões Mostrados");
        bt_Cartoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12), new java.awt.Color(204, 204, 255))); // NOI18N
        bt_Cartoes.setOpaque(true);
        bt_Cartoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CartoesMouseClicked(evt);
            }
        });
        bt_Cartoes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_CartoesMouseMoved(evt);
            }
        });

        bt_GolosMarcado.setBackground(new java.awt.Color(204, 204, 255));
        bt_GolosMarcado.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        bt_GolosMarcado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_GolosMarcado.setText("Golos Marcados");
        bt_GolosMarcado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12), new java.awt.Color(204, 204, 255))); // NOI18N
        bt_GolosMarcado.setOpaque(true);
        bt_GolosMarcado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_GolosMarcadoMouseClicked(evt);
            }
        });
        bt_GolosMarcado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_GolosMarcadoMouseMoved(evt);
            }
        });

        bt_GolosSofrido.setBackground(new java.awt.Color(204, 204, 255));
        bt_GolosSofrido.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        bt_GolosSofrido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_GolosSofrido.setText("Golos Sofridos");
        bt_GolosSofrido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12), new java.awt.Color(204, 204, 255))); // NOI18N
        bt_GolosSofrido.setOpaque(true);
        bt_GolosSofrido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_GolosSofridoMouseClicked(evt);
            }
        });
        bt_GolosSofrido.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_GolosSofridoMouseMoved(evt);
            }
        });

        bt_Defesas.setBackground(new java.awt.Color(204, 204, 255));
        bt_Defesas.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        bt_Defesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_Defesas.setText("Defesas Realizadas");
        bt_Defesas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12), new java.awt.Color(204, 204, 255))); // NOI18N
        bt_Defesas.setOpaque(true);
        bt_Defesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_DefesasMouseClicked(evt);
            }
        });
        bt_Defesas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_DefesasMouseMoved(evt);
            }
        });

        Tabela.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Número", "Clube", "Equipa", "Data de Início", "Data do Fim"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bt_Adicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Remover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Remover1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bt_Castigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Jogos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Cartoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_GolosMarcado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_GolosSofrido, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Defesas)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Castigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Jogos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Cartoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_GolosMarcado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_GolosSofrido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Defesas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(202, 202, 202)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Adicionar)
                    .addComponent(bt_Editar)
                    .addComponent(bt_Remover)
                    .addComponent(bt_Remover1))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        jLabel3.setText("Nome >>");

        lbl_Nome.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        lbl_Nome.setForeground(new java.awt.Color(255, 102, 102));
        lbl_Nome.setText("Fernando João");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        jLabel5.setText("Nº FAF >>");

        lbl_numFAF.setFont(new java.awt.Font("Trebuchet MS", 0, 14));
        lbl_numFAF.setForeground(new java.awt.Color(255, 51, 51));
        lbl_numFAF.setText("1000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Nome)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_numFAF)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lbl_Nome)
                    .addComponent(jLabel5)
                    .addComponent(lbl_numFAF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CastigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CastigoMouseClicked
        String nomeJogador=null;
        String numFAF1=null;
        String numHistorial1;
        long numHistorial;
        long numFAF=0;
                
        if (Tabela.getSelectedRowCount()==1){
            
            //JOptionPane.showMessageDialog(null, "Peguei","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
             
            //String valorSelecionado = Tabela.getValueAt(Tabela.getSelectedRow(),0).toString();
            //JOptionPane.showMessageDialog(null, valorSelecionado+"","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            nomeJogador= lbl_Nome.getText();
            numFAF1=lbl_numFAF.getText();
            numHistorial1=Tabela.getValueAt(Tabela.getSelectedRow(),0).toString();
            
            //JOptionPane.showMessageDialog(null, nomeClube+" nomeClube","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            //JOptionPane.showMessageDialog(null, numIdFiscal+" numIFiscal","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            numFAF= Long.parseLong(numFAF1);
            numHistorial= Long.parseLong(numHistorial1);
            
            //JOptionPane.showMessageDialog(null, idEquipa+" idEquipa ","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            frmCastigos Chamar =new frmCastigos(new javax.swing.JFrame(), true);
            Chamar.setNomeNumfaf(nomeJogador, numFAF);
            Chamar.actualizaTabela(numHistorial);
            Chamar.setVisible(true);              
        
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione um Clube!","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_bt_CastigoMouseClicked

    private void bt_CastigoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CastigoMouseMoved
        bt_Castigo.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_bt_CastigoMouseMoved

    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
        // TODO add your handling code here:
        bt_Castigo.setBackground(new java.awt.Color(204, 204, 255));
        bt_Jogos.setBackground(new java.awt.Color(204, 204, 255));
        bt_Cartoes.setBackground(new java.awt.Color(204, 204, 255));
        bt_GolosMarcado.setBackground(new java.awt.Color(204, 204, 255));
        bt_GolosSofrido.setBackground(new java.awt.Color(204, 204, 255));
        bt_Defesas.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_jPanel3MouseMoved

    private void bt_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AdicionarActionPerformed
        // TODO add your handling code here:
        frmAddHistorialJogador Chamar =new frmAddHistorialJogador(new javax.swing.JFrame(), true);
        Chamar.setNumFAF(Long.parseLong(lbl_numFAF.getText()));
        Chamar.inserirClubesCombo();
        Chamar.setVisible(true);
    }//GEN-LAST:event_bt_AdicionarActionPerformed

    private void bt_JogosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_JogosMouseClicked
        // TODO add your handling code here:
        String nomeJogador=null;
        String numFAF1=null;
        String idEquipa1;
        long idEquipa;
        long numFAF=0;
                
        if (Tabela.getSelectedRowCount()==1){
            
            //JOptionPane.showMessageDialog(null, "Peguei","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
             
            //String valorSelecionado = Tabela.getValueAt(Tabela.getSelectedRow(),0).toString();
            //JOptionPane.showMessageDialog(null, valorSelecionado+"","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            nomeJogador= lbl_Nome.getText();
            numFAF1=lbl_numFAF.getText();
            idEquipa1=Tabela.getValueAt(Tabela.getSelectedRow(),2).toString();
            
            
            //JOptionPane.showMessageDialog(null, nomeClube+" nomeClube","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            //JOptionPane.showMessageDialog(null, numIdFiscal+" numIFiscal","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            numFAF= Long.parseLong(numFAF1);
            idEquipa= Long.parseLong(idEquipa1);
            
            //JOptionPane.showMessageDialog(null, idEquipa+" idEquipa ","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            frmJogosParticipados Chamar =new frmJogosParticipados(new javax.swing.JFrame(), true);
            Chamar.setNomeNumfaf(nomeJogador, numFAF);
            Chamar.actualizaTabela(numFAF,idEquipa);
            Chamar.setVisible(true);              
        
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione um Clube!","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_bt_JogosMouseClicked

    private void bt_JogosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_JogosMouseMoved
        // TODO add your handling code here:
        bt_Jogos.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_bt_JogosMouseMoved

    private void bt_CartoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CartoesMouseClicked
        // TODO add your handling code here:
        String nomeJogador=null;
        String numFAF1=null;
        String idEquipa1;
        long idEquipa;
        long numFAF=0;
                
        if (Tabela.getSelectedRowCount()==1){
            
            //JOptionPane.showMessageDialog(null, "Peguei","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
             
            //String valorSelecionado = Tabela.getValueAt(Tabela.getSelectedRow(),0).toString();
            //JOptionPane.showMessageDialog(null, valorSelecionado+"","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            nomeJogador= lbl_Nome.getText();
            numFAF1=lbl_numFAF.getText();
            idEquipa1=Tabela.getValueAt(Tabela.getSelectedRow(),2).toString();
            
            
            //JOptionPane.showMessageDialog(null, nomeClube+" nomeClube","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            //JOptionPane.showMessageDialog(null, numIdFiscal+" numIFiscal","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            numFAF= Long.parseLong(numFAF1);
            idEquipa= Long.parseLong(idEquipa1);
            
            //JOptionPane.showMessageDialog(null, idEquipa+" idEquipa ","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            frmCartoesMostrados Chamar =new frmCartoesMostrados(new javax.swing.JFrame(), true);
            Chamar.setNomeNumfaf(nomeJogador, numFAF);
            Chamar.actualizaTabela(numFAF,idEquipa);
            Chamar.setVisible(true);              
        
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione um Clube!","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_bt_CartoesMouseClicked

    private void bt_CartoesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CartoesMouseMoved
        // TODO add your handling code here:
        bt_Cartoes.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_bt_CartoesMouseMoved

    private void bt_GolosMarcadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_GolosMarcadoMouseClicked
        // TODO add your handling code here:
        String nomeJogador=null;
        String numFAF1=null;
        String idEquipa1;
        long idEquipa;
        long numFAF=0;
                
        if (Tabela.getSelectedRowCount()==1){
            
            //JOptionPane.showMessageDialog(null, "Peguei","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
             
            //String valorSelecionado = Tabela.getValueAt(Tabela.getSelectedRow(),0).toString();
            //JOptionPane.showMessageDialog(null, valorSelecionado+"","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            nomeJogador= lbl_Nome.getText();
            numFAF1=lbl_numFAF.getText();
            idEquipa1=Tabela.getValueAt(Tabela.getSelectedRow(),2).toString();
            
            
            //JOptionPane.showMessageDialog(null, nomeClube+" nomeClube","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            //JOptionPane.showMessageDialog(null, numIdFiscal+" numIFiscal","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            numFAF= Long.parseLong(numFAF1);
            idEquipa= Long.parseLong(idEquipa1);
            
            //JOptionPane.showMessageDialog(null, idEquipa+" idEquipa ","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            frmGolosMarcados Chamar =new frmGolosMarcados(new javax.swing.JFrame(), true);
            Chamar.setNomeNumfaf(nomeJogador, numFAF);
            Chamar.actualizaTabela(numFAF,idEquipa);
            Chamar.setVisible(true);              
        
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione um Clube!","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_bt_GolosMarcadoMouseClicked

    private void bt_GolosMarcadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_GolosMarcadoMouseMoved
        // TODO add your handling code here:
        bt_GolosMarcado.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_bt_GolosMarcadoMouseMoved

    private void bt_GolosSofridoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_GolosSofridoMouseClicked
        // TODO add your handling code here:
        String nomeJogador=null;
        String numFAF1=null;
        String idEquipa1;
        long idEquipa;
        long numFAF=0;
                
        if (Tabela.getSelectedRowCount()==1){
            
            //JOptionPane.showMessageDialog(null, "Peguei","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
             
            //String valorSelecionado = Tabela.getValueAt(Tabela.getSelectedRow(),0).toString();
            //JOptionPane.showMessageDialog(null, valorSelecionado+"","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            nomeJogador= lbl_Nome.getText();
            numFAF1=lbl_numFAF.getText();
            idEquipa1=Tabela.getValueAt(Tabela.getSelectedRow(),2).toString();
            
            
            //JOptionPane.showMessageDialog(null, nomeClube+" nomeClube","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            //JOptionPane.showMessageDialog(null, numIdFiscal+" numIFiscal","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            numFAF= Long.parseLong(numFAF1);
            idEquipa= Long.parseLong(idEquipa1);
            
            //JOptionPane.showMessageDialog(null, idEquipa+" idEquipa ","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            frmGolosSofridos Chamar =new frmGolosSofridos(new javax.swing.JFrame(), true);
            Chamar.setNomeNumfaf(nomeJogador, numFAF);
            Chamar.actualizaTabela(numFAF,idEquipa);
            Chamar.setVisible(true);              
        
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione um Clube!","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_bt_GolosSofridoMouseClicked

    private void bt_GolosSofridoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_GolosSofridoMouseMoved
        // TODO add your handling code here:
        bt_GolosSofrido.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_bt_GolosSofridoMouseMoved

    private void bt_DefesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_DefesasMouseClicked
        // TODO add your handling code here:
        String nomeJogador=null;
        String numFAF1=null;
        String idEquipa1;
        long idEquipa;
        long numFAF=0;
                
        if (Tabela.getSelectedRowCount()==1){
            
            //JOptionPane.showMessageDialog(null, "Peguei","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
             
            //String valorSelecionado = Tabela.getValueAt(Tabela.getSelectedRow(),0).toString();
            //JOptionPane.showMessageDialog(null, valorSelecionado+"","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            nomeJogador= lbl_Nome.getText();
            numFAF1=lbl_numFAF.getText();
            idEquipa1=Tabela.getValueAt(Tabela.getSelectedRow(),2).toString();
            
            
            //JOptionPane.showMessageDialog(null, nomeClube+" nomeClube","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            //JOptionPane.showMessageDialog(null, numIdFiscal+" numIFiscal","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            numFAF= Long.parseLong(numFAF1);
            idEquipa= Long.parseLong(idEquipa1);
            
            //JOptionPane.showMessageDialog(null, idEquipa+" idEquipa ","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
            
            frmDefesasRealizadas Chamar =new frmDefesasRealizadas(new javax.swing.JFrame(), true);
            Chamar.setNomeNumfaf(nomeJogador, numFAF);
            Chamar.actualizaTabela(numFAF,idEquipa);
            Chamar.setVisible(true);              
        
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione um Clube!","Campeonato Angolano de Futebol", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_bt_DefesasMouseClicked

    private void bt_DefesasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_DefesasMouseMoved
        // TODO add your handling code here:
        bt_Defesas.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_bt_DefesasMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHistorialJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHistorialJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHistorialJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHistorialJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmHistorialJogadores dialog = new frmHistorialJogadores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton bt_Adicionar;
    private javax.swing.JLabel bt_Cartoes;
    private javax.swing.JLabel bt_Castigo;
    private javax.swing.JLabel bt_Defesas;
    private javax.swing.JButton bt_Editar;
    private javax.swing.JLabel bt_GolosMarcado;
    private javax.swing.JLabel bt_GolosSofrido;
    private javax.swing.JLabel bt_Jogos;
    private javax.swing.JButton bt_Remover;
    private javax.swing.JButton bt_Remover1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_numFAF;
    // End of variables declaration//GEN-END:variables
}
